# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:q-fin.*'

# 検索キーワード
keywords:
        climate: 10
        deep hedging: 10
        anomaly detection: 1
        neural network: 3
        deep learning: 3
        reinforcement learning: 5
        generative adversalial network: 3
        gan: 3
        vae: 3

# 通知の閾値
score_threshold: 2
