# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:q-fin.*'

# 検索キーワード
keywords:
        climate: 3
        deep hedging: 3
        anomaly detection: 1
        neural network: 2
        deep learning: 2
        reinforcement learning: 3
        generative adversalial network: 1
        gan: 1
        vae: 1

# 通知の閾値
score_threshold: 2
